CREATE DATABASE IF NOT EXISTS HOTEL_Database;
USE HOTEL_Database;

CREATE TABLE HOTEL
(
    no      INT PRIMARY KEY CHECK (no BETWEEN 1 AND 5),
    name    VARCHAR(30) NOT NULL,
    address VARCHAR(50) NOT NULL
);